### ISSUE TITLE
Warning (emacs): PUML Preview failed: exited abnormally with code 1

### ISSUE THREAD

**Issue by Vic-Wu** [skuro/puml-mode#10]
I use Spacemacs and when I preview diagram I get this warningl

**Comment by sergej-koscejev** [comment]
I get this on Emacs 25.0.50 (mingw64) as well. No idea why, I think I have everything set up properly.

**Comment by skuro** [comment]
I also assume that the preview is broken, right?

**Comment by nivekuil** [comment]
Does it work if your plantuml.jar is in the default `puml-plantuml-jar-path`? I had the same error; it turns out you have to expand a custom path yourself, like `/home/user/.emacs.d/plantuml.jar` instead of `~/.emacs.d/plantuml.jar`.

**Comment by mickael-kerjean** [comment]
I made a dirty fix that works on my machine. Instead of:
``` lisp
 (let ((ps (start-process "PUML" buf
                             "java" "-jar" (shell-quote-argument puml-plantuml-jar-path)
                             (puml-output-type-opt) "-p")))
```
I now have
``` lisp
 (let ((ps (start-process "PUML" buf
                             "java" "-jar" (convert-standard-filename puml-plantuml-jar-path)
                             (puml-output-type-opt) "-p")))
```

**Comment by mickael-kerjean** [comment]
Some background information about the error:
1) The debug message in the *PUML Preview* buffer says: 
```
Error: Unable to access jarfile c\:/Users/sesa369698/plantuml.jar
```

2) making use of shell-quote-argument on windows:
``` lisp
(shell-quote-argument puml-plantuml-jar-path) => c\\:/Users/sesa369698/plantuml.jar
```

I can't find any way to make this path to work on the window using the default shell

**Comment by svargellin** [comment]
Don't you use Emacs with cygwin bash shell? Maybe you should use path like this /cygdrive/c/Users/sesa369698/plantuml.jar.
I've found a thread with emacs' bugreport relates to the matter:
http://gnu.emacs.bug.narkive.com/EGvLya5N/bug-20744-shell-quote-argument-in-emacs-24-5-and-emacs-25-on-windows-cannot-figure-out-path#post14
They decided to stop quoting colon in the function.

**Comment by skuro** [comment]
@mickael-kerjean I don't have a Windows machine at the moment to test it out, but could you please try if combining both function works on your end?

```
(shell-quote-argument (convert-standard-filename puml-plantuml-jar-path))
```

**Comment by mickael-kerjean** [comment]
@skuro same issue:
``` lisp
(shell-quote-argument (convert-standard-filename puml-plantuml-jar-path)) => C\\:/Users/sesa369698/plantuml.jar
```
@svargellin no Cygwin (weird error and wasn't patient enough to make it work properly with emacs). Indeed it seems related to this bug report. 

I'll stay with the dirty hack that do the job as expected

**Comment by Vic-Wu** [comment]
@mickael-kerjean Thank you. I have fixed the problem with the dirty way.

**Comment by 5alamander** [comment]
@mickael-kerjean Thanks.
