### ISSUE TITLE
Document integration with org-src for C-' editing

### ISSUE THREAD

**Issue by olberger** [skuro/puml-mode#20]
Hi.

May I suggest to add to the documentation that it's possible to use puml-mode from withing org-mode with C-' when the following was done:  
(add-to-list 'org-src-lang-modes '("plantuml" . puml))

Hope this helps.

**Comment by skuro** [comment]
Hi @olberger, thanks for the suggestion, I added a bit of documentation in the usage section describing what you suggested.
