### ISSUE TITLE
Unable to Preview using Mac Emacs 25.1

### ISSUE THREAD

**Issue by zhuoqiang** [skuro/puml-mode#21]
## Environment

- PlantUML.jar is successfully installed with manual invoke OK
- Mac 10.11.5
- GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.2.0, NS appkit-1404.34 Version 10.11.2 (Build 15C50))

The configuration is as following:

```lisp
;; Enable puml-mode for PlantUML files
(setq puml-plantuml-jar-path "Users/myname/bin/plantuml.jar")
(require 'puml-mode)
(add-to-list 'auto-mode-alist '("\\.puml\\'" . puml-mode))
(add-to-list 'auto-mode-alist '("\\.plantuml\\'" . puml-mode))
```
When preview with `C-c C-c` it shows error message:

```
error in process sentinel: if: PUML Preview failed: exited abnormally with code 1
```

**Comment by zhuoqiang** [comment]
I just notice that the path is not set correctly:, it should be `/Users/myname/bin/plantuml.jar` instead of `Users/myname/bin/plantuml.jar`.

Add the missing leading **/** fixed this issue.

**Comment by skuro** [comment]
Good to hear that everything worked ok. Maybe some extra checks / logging might help understanding what's going on.
